= Functional Subsystem- and System-Tests (API + UI)

This article focuses on Subsystem- and System-Tests. General test automation good practices can be found xref:test_automation.adoc[here].

== General Good Practices

=== Use BDD to develop test scenarios
https://cucumber.io/docs/bdd/[Behavior Driven Development (BDD)] is a software development method that generates a common understanding by conversations with business, developers and testers about how the system should behave.
The wanted behavior is captured in scenarios with concrete example data in the so called https://cucumber.io/docs/gherkin/reference/[Gherkin] syntax.
The syntax mainly consists of natural language with business terms in a given - when - then - structure.
The scenarios are defined before implemenation starts, so that the implementation can take the right direction from the beginning.
BDD tools allow automing the scenarios directly as automated tests. 

Typical Tool: https://cucumber.io/[Cucumber]

==== BDD good and bad practices
https://automationpanda.com/2017/01/30/bdd-101-writing-good-gherkin/

Most important:

* Collaborate with business, dev and test
* Short scenarios (leave out irrelevant data, combine UI steps)
* Do NOT use Generic UI steps

=== Mix API and UI steps
Just because your expected result can only be checked in the UI does not mean your whole test must be executed via UI.
You can use the API to create you preconditions and the perform some step in the UI.
This makes the complete test faster and more reliable.

=== Prevent explicit waiting

Selenium implicit wait

Typical tool: Awaitility


=== Apply a rerun for failed tests

Cucumber, Maven surefire features

=== Make tests transparent and analyzable by proper reporting
Typical toolss:

* Combination with Test Management e.g. in Jira / Xray for better collaboration with BU: aggregated view, business view on coverage (BU, BA, tester)
* Jenkins Cucumber plugin: execution times per step + analysis of pipeline failure (dev)
* Allure reporting (dev, tester)
* Pushing metrics to Kibana or Influx + Grafana: aggregated view on execution times and stability (dev, architect)


== API-related Good Practices

====
*API-test* in this section means a functional test that uses API calls to trigger or check functionality of a fully integrated system under test.
This is a difference to unit testing of a method that exposes an endpoint via REST.
====

Typical Tool: RestAssured
TODO: example

=== Hide API authentication at a central point

=== Mock external system that are not in your scope
Typical tool: Wiremock


== UI-related Good Practices

====
*UI-test* in this section means a functional test that uses UI calls to trigger or check functionality of a fully integrated system under test.
This is a difference to Unit- or Unit-Integration Testsof a UI components.
====

Typical tool: Selenuim

=== Encapsulate UI technology specific logic in page objects

=== Reflect UI components in your test code

=== Add screenshots to the result report


== Test Data Good Practices

=== Keep references to data in the database at a central place

=== Use test data builders with defaults for complex structures

== Test Execution Good Practices

=== Ensure Fail Fast in pipelines
* Parallel exection (surefire or cucumber)
* Tag-wise (e.g. nightly)

=== Simplify environment setup for local tests
* Test Containers
**  with Quarkus
* Local Stack